---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: petstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petstore
    spec:
      initContainers:
        - name: init-networking
          image: olensmar/openapi-sidecar-init:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: service
          image: swaggerapi/petstore3:unstable
          ports:
            - containerPort: 8080
        - name: proxy
          image: olensmar/openapi-sidecar:latest
          ports:
            - containerPort: 8000