const helmCommonOptions = {
  '--atomic': 'boolean',
  '--ca-file': 'string',
  '--create-namespace': 'boolean',
  '--dependency-update': 'boolean',
  '--description': 'string',
  '--devel': 'boolean',
  '--disable-openapi-validation': 'boolean',
  '--dry-run': 'boolean',
  '--generate-name': 'boolean',
  '--help': 'boolean',
  '--insecure-skip-tls-verify': 'boolean',
  '--key-file': 'string',
  '--keyring': 'string',
  '--name-template': 'string',
  '--no-hooks': 'boolean',
  '--pass-credentials': 'boolean',
  '--password': 'string',
  '--post-renderer': 'string',
  '--render-subchart-notes': 'boolean',
  '--replace': 'boolean',
  '--repo': 'string',
  '--set': 'stringArray',
  '--set-file': 'stringArray',
  '--set-string': 'stringArray',
  '--skip-crds': 'boolean',
  '--timeout': 'duration',
  '--username': 'string',
  '--values': 'string',
  '--verify': 'boolean',
  '--version': 'string',
  '--wait': 'boolean',
  '--wait-for-jobs': 'boolean',
} as const;

export const helmInstallOptions = {
  ...helmCommonOptions,
  '--output': 'string', // ['table', 'json', 'yaml'],
} as const;

export const helmTemplateOptions = {
  ...helmCommonOptions,
  '--api-versions': 'stringArray',
  '--cert-file': 'string',
  '--include-crds': 'boolean',
  '--is-upgrade': 'boolean',
  '--kube-version': 'string',
  '--output-dir': 'string',
  '--release-name': 'boolean',
  '--show-only': 'stringArray',
  '--skip-tests': 'boolean',
  '--validate': 'boolean',
} as const;
