const hotkeys = {
  PREVIEW_CLUSTER: 'ctrl+i,command+i',
  TOGGLE_SETTINGS: `ctrl+\, , command+\,`,
  EXIT_PREVIEW_MODE: 'esc',
  SELECT_FOLDER: 'ctrl+o,command+o',
  REFRESH_FOLDER: 'ctrl+f5,command+f5',
  TOGGLE_LEFT_PANE: 'ctrl+b,command+b',
  ZOOM_IN: 'ctrl+=,command+=',
  ZOOM_OUT: 'ctrl+-,command+-',
  TOGGLE_RIGHT_PANE: 'ctrl+alt+b,command+alt+b',
  SAVE: 'ctrl+s,command+s',
  SELECT_FROM_HISTORY_BACK: 'alt+left',
  SELECT_FROM_HISTORY_FORWARD: 'alt+right',
  OPEN_NEW_RESOURCE_WIZARD: 'ctrl+n,cmd+n',
  CREATE_NEW_RESOURCE: 'shift+enter',
  APPLY_SELECTION: 'ctrl+alt+s,cmd+alt+s',
  DIFF_RESOURCE: 'ctrl+alt+d,cmd+alt+d',
  OPEN_EXPLORER_TAB: 'ctrl+shift+e, command+shift+e',
  OPEN_KUSTOMIZATION_TAB: 'ctrl+shift+k, command+shift+k',
  OPEN_HELM_TAB: 'ctrl+shift+h, command+shift+h',
  RESET_RESOURCE_FILTERS: 'ctrl+alt+r, command+alt+r',
  OPEN_QUICK_SEARCH: 'ctrl+p, ctrl+shift+p, command+p, command+shift+p',
  OPEN_GETTING_STARTED_PAGE: 'ctrl+shift+n, command+shift+n',
};

export default hotkeys;
